<footer>
    <section>
        <img src="images/footer-logo.png" alt="Swinburne logo">
        <table>
            <tr>
                <td><a href="index.php">Home</a></td>
            </tr>
            <tr>
                <td><a href="about.php#contact-us">Contact Us</a></td>
            </tr>
            <tr>
                <td><a href="job.php">Job</a></td>
            </tr>
            <tr>
                <td><a href="apply.php">Apply</a></td>
            </tr>
        </table>
    </section>
    <hr>
    <ul class="footer-emails">
        <li>
            <a href="mailto:102560056@student.swin.edu.au">
                <img src="images/email.svg" alt="email icon">
                <p>Sam Banfield</p>
            </a>
        </li>
        <li>
            <a href="mailto:104119968@student.swin.edu.au">
                <img src="images/email.svg" alt="email icon">
                <p>Saffan Malik</p>
            </a>
        </li>
        <li>
            <a href="mailto:104453323@student.swin.edu.au">
                <img src="images/email.svg" alt="email icon">
                <p>Preston Hulme</p>
            </a>
        </li>
        <li>
            <a href="mailto:104147451@student.swin.edu.au">
                <img src="images/email.svg" alt="email icon">
                <p>Lexi Peng</p>
            </a>
        </li>
        <li>
            <a href="mailto:103163537@student.swin.edu.au">
                <img src="images/email.svg" alt="email icon">
                <p>Randew Kumarasinghe</p>
            </a>
        </li>
    </ul>
</footer>